### ISSUE TITLE
[First Timers Only] Display link to subscription statements

### ISSUE THREAD

**Issue by stevenmaguire** [delivered/chargify-zendesk#1]
In some cases we won't display all the native data associated with a subscription because it requires additional API calls. Instead we can provide a link to the resource within the Chargify account itself. 

An [example of this treatment](https://github.com/delivered/chargify-zendesk/blob/master/templates/customerPage.hdbs#L72) already exists in the code.

Statements are a significant piece of associated data for subscriptions. It would be great to display a link that opens a given subscription's statements in the Chargify account itself, in a new tab.

**Comment by udayapitchika** [comment]
Shall I take this issue as well in the same way as issue #2?

I can add a centered link that says `View Statements?` below this `View Transactions?`.

**Comment by stevenmaguire** [comment]
@udayapitchika you are on a roll. Considering that you are working on the other issue, I would ask that you leave this one open for another person to contribute. These `first-timers-only` issues are designed to help new people get started contributing to a project.

There's a short list of more advanced opportunities for this project at the bottom of the [blog post I wrote about this project](https://www.earthclassmail.com/blog/chargify-app-for-zendesk-open-source).

**Comment by udayapitchika** [comment]
@stevenmaguire sure, I will leave this open for others. 
Thanks for the blog post, I'll definitely check those opportunities.

**Comment by nawazishali** [comment]
Hey @stevenmaguire ,

I would like try this one out. Please share details on this issue.

**Comment by stevenmaguire** [comment]
@nawazishali Please review the [contributing guide](https://github.com/delivered/chargify-zendesk/blob/master/CONTRIBUTING.md). Fork this repository, pull your fork down locally, then get the application up and running locally. From there you can implement the feature requested here and then submit a pull request.

**Comment by evanscloud** [comment]
@stevenmaguire I was wondering if this issue is still open? I would like a chance to work on this if it is. First timer here :)

**Comment by stevenmaguire** [comment]
@evanscloud go for it!
