### ISSUE TITLE
[First Timers Only] Display link to subscription transactions 

### ISSUE THREAD

**Issue by stevenmaguire** [delivered/chargify-zendesk#2]
In some cases we won't display all the native data associated with a subscription because it requires additional API calls. Instead we can provide a link to the resource within the Chargify account itself. 

An [example of this treatment](https://github.com/delivered/chargify-zendesk/blob/master/templates/customerPage.hdbs#L72) already exists in the code.

Transactions are a significant piece of associated data for subscriptions. It would be great to display a link that opens a given subscription's transactions in the Chargify account itself, in a new tab.

**Comment by goti921** [comment]
I would like to contribute. Any more details ?

**Comment by krys2fa** [comment]
I'm also interested in contributing. Kindly provide further information.

**Comment by stevenmaguire** [comment]
Please review the [contributing guide](https://github.com/delivered/chargify-zendesk/blob/master/CONTRIBUTING.md). Fork this repository, pull your fork down locally, then get the application up and running locally. From there you can implement the feature requested here and then submit a pull request.

**Comment by shivasheeshyadav** [comment]
Hey,
I would like to work on this issue.

**Comment by stevenmaguire** [comment]
Ok! Please review the contributing guide. Fork this repository, pull your fork down locally, then get the application up and running locally. From there you can implement the feature requested here and then submit a pull request.

**Comment by shivasheeshyadav** [comment]
Ok. Please add "hacktoberfest" label to this issue, and assign it to me.

**Comment by stevenmaguire** [comment]
I will add the label. I cannot assign you because you are not in the delivered organization. You are welcome to submit a Pull Request with your solution, as is anyone else for that matter.

**Comment by shivasheeshyadav** [comment]
@stevenmaguire I've forked the repo. Now how do i run it locally on my machine ? What will be the subdomain ?

**Comment by stevenmaguire** [comment]
To run the project locally, you will need to follow these instructions from the [contributing guide](https://github.com/delivered/chargify-zendesk/blob/master/CONTRIBUTING.md): 

```
Getting started:

Install the zat gem - $ gem install zendesk_apps_tools
Run the server - $ zat server
Preview the app - bring up zendesk, find a user or ticket, and add zat=true query string parameters to the url, like this:
  https://{your-subdomain}.zendesk.com/agent/users/{user-id}/requested_tickets?zat=true
    NOTE: if a shield icon appears in the browser, click on on and allow the script to run
  reload the app to make changes active
```

After `$ zat server` and before `Preview the app` will be prompted for an api_key and chargify subdomain. These need to be for a chargify account that you have access to.

**Comment by shivasheeshyadav** [comment]
@stevenmaguire So do I have to create a chargify account then ?

**Comment by stevenmaguire** [comment]
Yes. Or gain access to an existing one with sample data. You will also need to have access to a Zendesk account as well. Do you have those?

**Comment by shivasheeshyadav** [comment]
No. Neither I have access to any chargify account with sample data nor to a Zendesk account.

**Comment by stevenmaguire** [comment]
Ah, that is definitely a roadblock for this particular project. You will need those things before beginning.

**Comment by udayapitchika** [comment]
@stevenmaguire do you have a preferred position where the link to subscription transactions should appear? Is it okay if it is placed just below the ID ?

Also what should be the label and the link text for the field ? For now, I'm setting the label as "Transactions" and link text as "Click Here". Below is the preview of how it appears -

![image](https://cloud.githubusercontent.com/assets/12501855/19500489/c3b0be84-956b-11e6-8c55-502bcd018715.png)

The link will take the user to a new tab and opens the subscription's transactions in the Chargify account itself.

Please provide your feedback.

**Comment by stevenmaguire** [comment]
@udayapitchika Thanks for taking putting some energy into this. Because this link does not contain any practical information about the subscription, I feel like it does not belong in such a prominent location. 

What do you think about a full width row at the bottom of the table with a centered link that says `View Transactions`?

```html
<tr>
    <td colspan="2" style="text-align: center;">
        <a href="#">View Transactions</a>
    </td>
</tr>
```

The above example does not have the handlerbars code to place the url and also includes inline CSS. Perhaps you can improve upon that a bit?

**Comment by udayapitchika** [comment]
Thanks for the feedback @stevenmaguire. I really appreciate it.

I agree with you on the point that it doesn't belong on the top. I can update the handlebars code and improve the css.

**Comment by stevenmaguire** [comment]
https://github.com/delivered/chargify-zendesk/releases/tag/1.4.0 has been cut which addresses this issue. Thanks @udayapitchika!
