### ISSUE TITLE
Support for multiple sub-domains?

### ISSUE THREAD

**Issue by jmatthewpryor** [delivered/chargify-zendesk#3]
Hi
We use 2 different sub-domains based but one ZenDesk instance
How hard would it be to cater for more than one sub-domain?
Thanks

**Comment by stevenmaguire** [comment]
Have you tried installing the app twice with two different names? One for each subdomain/api key combo?

I don't think the actual handling of data from two subdomains would be a problem. The issues would likely arise from the settings configuration, that is managing an N number of subdomains/api keys in a Zendesk App fashion.

**Comment by stevenmaguire** [comment]
I was able to install a second copy of the app and provide a new subdomain and api key. I would recommend doing that for the time being :)

**Comment by stevenmaguire** [comment]
Additionally, I just cut a new release that includes an updated app header that displays the subdomain as a link to the Chargify site. This, combined with the distinct app name used when installing the second instance should help your users distinguish between the two Chargify apps.

https://github.com/delivered/chargify-zendesk/releases/tag/1.3.0

**Comment by jmatthewpryor** [comment]
thanks very much - works well for me
