### ISSUE TITLE
Zendesk requires v2 of their Framework to be used as an app

### ISSUE THREAD

**Issue by SInCE** [delivered/chargify-zendesk#8]
Hi,

I would really like to use your integration, however I wasn't able to install it as an app in our zendesk application, as it was rejected saying "v2 Zendesk Framework is required". Would it be possible to update your integration to support v2 accordingly please?

I'm looking forward to your feedback!

**Comment by stevenmaguire** [comment]
Closing in favor of another issue with a call for help to upgrade.

https://github.com/delivered/chargify-zendesk/issues/9
